server:
  port: 8081
servlet:
  context-path: /wuzu-loan-backstage-porvider
spring:
 datasource:
    url: jdbc:mysql://192.168.31.9:3308/loan
    username: wzm
    password: root
    driver-class-name: com.mysql.jdbc.Driver